//! Native playback audit; fixture videos are generated by `just local-player-audit`.
use adw::prelude::*;
use gtk::{gio, glib, gsk};
use std::{
    cell::{Cell, RefCell},
    path::PathBuf,
    time::Duration,
};

fn descendants(root: &gtk::Widget) -> Vec<gtk::Widget> {
    let mut result = vec![root.clone()];
    let mut child = root.first_child();
    while let Some(widget) = child {
        result.extend(descendants(&widget));
        child = widget.next_sibling();
    }
    result
}
fn find(root: &gtk::Widget, id: &str) -> gtk::Widget {
    descendants(root)
        .into_iter()
        .find(|widget| widget.buildable_id().as_deref() == Some(id))
        .expect(id)
}
fn position(root: &gtk::Widget) -> f64 {
    find(root, "video_scale")
        .downcast::<gtk::Scale>()
        .unwrap()
        .value()
}
fn player(root: &gtk::Widget) -> gtk::Widget {
    descendants(root)
        .into_iter()
        .find(|widget| widget.type_().name() == "MPVPage")
        .unwrap()
}
fn screenshot(window: &tsukimi::Window, directory: &std::path::Path, name: &str) -> bool {
    let snapshot = gtk::Snapshot::new();
    gtk::WidgetPaintable::new(Some(window)).snapshot(
        &snapshot,
        window.width() as f64,
        window.height() as f64,
    );
    let Some(node) = snapshot.to_node() else {
        window.queue_draw();
        return false;
    };
    let renderer = gsk::Renderer::for_surface(&window.surface().unwrap()).unwrap();
    let texture = renderer.render_texture(&node, None);
    let path = directory.join(format!("local-{name}.png"));
    texture.save_to_png(&path).unwrap();
    renderer.unrealize();
    let pixels = image::open(path).unwrap().to_rgb8();
    assert!(
        pixels
            .pixels()
            .any(|pixel| pixel[0] > 180 && pixel[1] < 100),
        "Missing rendered test video"
    );
    assert!(
        pixels
            .pixels()
            .any(|pixel| pixel[1] > 180 && pixel[0] < 100),
        "Missing rendered test video"
    );
    println!(
        "PASS screenshot {name}: {}x{}",
        window.width(),
        window.height()
    );
    true
}

fn main() {
    let directory =
        PathBuf::from(std::env::var_os("TSUKIMI_LOCAL_AUDIT_DIR").expect("Audit output path"));
    let directory = std::path::absolute(directory).unwrap();
    let fixture = directory.join("videos/Episode 2.mp4");
    let stage = Cell::new(0);
    let ticks = Cell::new(0);
    let private_root = std::rc::Rc::new(RefCell::new(None::<PathBuf>));
    let root_after_run = private_root.clone();
    let completed = std::rc::Rc::new(Cell::new(false));
    let completed_after_run = completed.clone();
    // Register a source before initialization, without initializing GTK/GSettings first.
    glib::timeout_add_local(Duration::from_millis(800), move || {
        ticks.set(ticks.get() + 1);
        assert!(
            ticks.get() < 65,
            "Local player audit timed out at stage {}",
            stage.get()
        );
        let Some(window) = gtk::Window::list_toplevels()
            .into_iter()
            .find(|window| window.is_visible())
            .and_downcast::<tsukimi::Window>()
        else {
            return glib::ControlFlow::Continue;
        };
        let root = window.upcast_ref::<gtk::Widget>();
        if std::env::var_os("LOCAL_AUDIT_EMPTY").is_some() {
            assert!(window.local_playlist().is_none());
            assert!(
                once_cell::sync::Lazy::get(&tsukimi::client::jellyfin_client::JELLYFIN_CLIENT)
                    .is_none()
            );
            *private_root.borrow_mut() = std::env::var_os("MPV_HOME")
                .map(PathBuf::from)
                .map(|path| path.parent().unwrap().to_path_buf());
            println!("PASS empty player closes without an active video");
            completed.set(true);
            window.close();
            return glib::ControlFlow::Break;
        }
        let Some(playlist) = window.local_playlist() else {
            return glib::ControlFlow::Continue;
        };
        assert!(
            once_cell::sync::Lazy::get(&tsukimi::client::jellyfin_client::JELLYFIN_CLIENT)
                .is_none(),
            "Local playback touched the server client"
        );
        let video = descendants(root)
            .into_iter()
            .find(|widget| widget.type_().name() == "MPVGLArea")
            .unwrap()
            .downcast::<gtk::GLArea>()
            .unwrap();
        assert!(video.error().is_none(), "GLArea error: {:?}", video.error());
        match stage.get() {
            0 => {
                gtk::Settings::default()
                    .unwrap()
                    .set_property("gtk-enable-animations", false);
                if position(root) < 1.0 {
                    return glib::ControlFlow::Continue;
                }
                assert!(tsukimi::local_player_mode());
                assert_eq!(
                    window.application().unwrap().application_id().as_deref(),
                    Some(tsukimi::LOCAL_PLAYER_APP_ID)
                );
                assert_eq!(std::env::var("GSETTINGS_BACKEND").unwrap(), "memory");
                *private_root.borrow_mut() = std::env::var_os("MPV_HOME")
                    .map(PathBuf::from)
                    .map(|path| path.parent().unwrap().to_path_buf());
                assert_eq!(playlist.files().len(), 4);
                assert!(playlist.current_file().ends_with("Episode 2.mp4"));
                assert!(position(root) < 5.0, "Unexpected resume position");
                if !screenshot(&window, &directory, "playback") {
                    return glib::ControlFlow::Continue;
                }
                player(root)
                    .activate_action("mpv.next-video", None)
                    .unwrap();
                println!(
                    "PASS direct launch, folder filtering, selected file, video rendering, no server client"
                );
            }
            1 => {
                assert!(playlist.current_file().ends_with("Episode 10.MP4"));
                if position(root) < 1.0 {
                    return glib::ControlFlow::Continue;
                }
                assert!(position(root) < 5.0);
                player(root)
                    .activate_action("mpv.previous-video", None)
                    .unwrap();
            }
            2 => {
                assert!(playlist.current_file().ends_with("Episode 2.mp4"));
                let list = find(root, "mpv_playlist")
                    .downcast::<gtk::ListView>()
                    .unwrap();
                let index = playlist
                    .files()
                    .iter()
                    .position(|path| path.ends_with("电影 空格.mp4"))
                    .unwrap() as u32;
                list.emit_by_name::<()>("activate", &[&index]);
            }
            3 => {
                assert!(playlist.current_file().ends_with("电影 空格.mp4"));
                if position(root) < 1.0 {
                    return glib::ControlFlow::Continue;
                }
                window.view_playlist();
                println!("PASS previous/next, clickable playlist and Unicode/spaces");
            }
            4 => {
                if !screenshot(&window, &directory, "playlist") {
                    return glib::ControlFlow::Continue;
                }
                root.activate_action("win.settings", None).unwrap();
            }
            5 => {
                if !screenshot(&window, &directory, "settings") {
                    return glib::ControlFlow::Continue;
                }
                window.view_media_info();
            }
            6 => {
                if !screenshot(&window, &directory, "media-info") {
                    return glib::ControlFlow::Continue;
                }
                window.view_media_info();
                gio::Settings::new(tsukimi::APP_ID)
                    .set_int("mpv-seek-forward-step", 60)
                    .unwrap();
                let index = playlist
                    .files()
                    .iter()
                    .position(|path| path.ends_with("Episode 2.mp4"))
                    .unwrap();
                window.play_local_index(index);
            }
            7 => {
                if position(root) < 1.0 {
                    return glib::ControlFlow::Continue;
                }
                player(root).activate_action("mpv.forward", None).unwrap();
            }
            8 => {
                if !playlist.current_file().ends_with("Episode 10.MP4") || position(root) < 1.0 {
                    return glib::ControlFlow::Continue;
                }
                println!("PASS automatic next-video after EOF");
                window.open_local_file(directory.join("videos/notes.txt"));
            }
            9 => {
                assert!(
                    playlist.current_file().ends_with("Episode 10.MP4"),
                    "Invalid file changed playback"
                );
                window.open_local_file(fixture.clone());
            }
            10 => {
                if !playlist.current_file().ends_with("Episode 2.mp4") || position(root) < 1.0 {
                    return glib::ControlFlow::Continue;
                }
                assert!(position(root) < 5.0, "Reopened file resumed playback");
                window.play_local_index(playlist.files().len() - 1);
            }
            11 => {
                if position(root) < 1.0 {
                    return glib::ControlFlow::Continue;
                }
                player(root).activate_action("mpv.forward", None).unwrap();
            }
            12 => {
                let page = descendants(root)
                    .into_iter()
                    .find(|widget| widget.type_().name() == "MPVPage")
                    .unwrap();
                if !page.property::<bool>("paused") {
                    return glib::ControlFlow::Continue;
                }
                assert_eq!(playlist.current_index(), playlist.files().len() - 1);
                assert!(!window.step_local_video(1));
                assert!(window.is_visible(), "Last-file EOF closed the player");
                println!("PASS final EOF, invalid file handling, reopen starts at zero");
                completed.set(true);
                window.close();
                return glib::ControlFlow::Break;
            }
            _ => unreachable!(),
        }
        stage.set(stage.get() + 1);
        glib::ControlFlow::Continue
    });
    let result = tsukimi::run();
    assert_eq!(result, glib::ExitCode::SUCCESS);
    assert!(completed_after_run.get(), "Audit did not complete");
    assert!(
        !root_after_run.borrow().as_ref().unwrap().exists(),
        "Private runtime was not removed"
    );
    let log = std::env::args()
        .collect::<Vec<_>>()
        .windows(2)
        .find(|pair| pair[0] == "--log-file")
        .map(|pair| PathBuf::from(&pair[1]))
        .expect("Audit needs a log trap");
    assert!(!log.exists(), "Local mode wrote a persistent log");
    println!("PASS no persistent log, private runtime cleaned up");
}
